<?php
/**
 * Created by PhpStorm.
 * User: Krasen
 * Date: 16/8/16
 * Time: 10:29
 * Email: jhasheng@hotmail.com
 */

namespace SS;


use Swoole\Buffer;

class SuperBuffer extends Buffer
{

    public function substr2Hex($offset, $length = -1, $remove = true)
    {
        $str = parent::substr($offset, $length, $remove); // TODO: Change the autogenerated stub
        return bin2hex($str);
    }

    public function substr2Dec($offset, $length = -1, $remove = true)
    {
        $str = $this->substr2Hex($offset, $length, $remove);
        return hexdec($str);
    }
}